#!/usr/bin/env bash

# shellcheck disable=SC1091
source ./modules/variables.sh
source ./modules/helpers.sh
source ./modules/credentials.sh
source ./modules/api.sh
source ./modules/ui.sh

# ------------------------ environment variables check ----------------------- #

invoke_subcommand "$1" "${*:2}"
